"""bugfix column

Revision ID: 24502fbddf8a
Revises: 8df2aca3cf5f
Create Date: 2020-04-04 12:36:42.299335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24502fbddf8a'
down_revision = '8df2aca3cf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch', sa.Column('body', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch', 'body')
    # ### end Alembic commands ###
