"""add dispatch description

Revision ID: 2987147643e3
Revises: f9d221c8fce6
Create Date: 2020-04-15 10:01:41.497737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2987147643e3'
down_revision = 'f9d221c8fce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch', sa.Column('description', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch', 'description')
    # ### end Alembic commands ###
