"""empty message

Revision ID: fe2ad502f29f
Revises: f2a9aeafe73e
Create Date: 2020-04-05 15:54:53.817158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2ad502f29f'
down_revision = 'f2a9aeafe73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch', 'name')
    # ### end Alembic commands ###
